import {notFound} from "next/navigation";
import {AppShell} from "../../components/app-shell";
import {PageHeader} from "../../components/page-header";
const sections = {
  projects:{eyebrow:"Projects",title:"Projects",description:"Manage project records, assignments, quotes, documents, and activity.",action:"New Project",columns:["Project #","Project","Customer","Status","Assigned To","Quotes","Project Total"],rows:[["26-0148","Glynn County Public Safety","Glynn County","Estimating","Kyle Jackson","3","$709,650"],["26-0154","Central High School","Metro Schools","Submitted","Kyle Jackson","2","$1,871,000"]]},
  documents:{eyebrow:"Documents",title:"Document Portal",description:"Global access to project files, controlled document sets, revisions, and review status.",action:"Upload",columns:["Name","Project","Type","Revision","Status","Modified"],rows:[["Glynn County Bid Drawings.pdf","Glynn County Public Safety","Drawing Set","Original","Review Required","Sep 12"],["Fire Alarm Pricing Comparison.xlsx","Glynn County Public Safety","Working File","—","Current","Sep 11"]]},
  quotes:{eyebrow:"Estimating",title:"Quotes",description:"Independent quotes inside projects with preserved revisions and automatic project rollups.",action:"New Quote",columns:["Quote #","Project","Quote","Version","Status","Estimator","Sell"],rows:[["26-0148-FA","Glynn County Public Safety","Fire Alarm","0.2","Submitted","Kyle Jackson","$186,400"],["26-0148-AV","Glynn County Public Safety","AV","0.0","Draft","Kyle Jackson","$94,750"]]},
  "rules-engine":{eyebrow:"Automation",title:"ScopeLogic Rules Engine",description:"Convert quantities and project conditions into transparent estimating recommendations.",action:"New Rule",columns:["Rule","Category","Status","Version","Behavior"],rows:[["Single Data Outlet","Data","Published","1.0","Recommend BOM"],["Paint Coverage","Painting","Draft","0.2","Calculate Only"]]},
  crm:{eyebrow:"CRM",title:"Customers & Opportunities",description:"Optional lightweight CRM that never blocks project or quote creation.",action:"New Opportunity",columns:["Company","Opportunity","Stage","Owner","Value"],rows:[["Glynn County","Public Safety Building","Estimating","K. Jackson","$709,650"]]},
  reports:{eyebrow:"Reports",title:"Reporting",description:"Reporting will expand after Alpha data and workflows are proven.",columns:["Report","Status","Purpose"],rows:[["Quote Pipeline","Planned","Submitted, awarded, and lost value"],["Pricing Changes","Planned","Catalog and vendor cost movement"]]},
  administration:{eyebrow:"Administration",title:"Company Settings",description:"Users, permissions, terminology, numbering, proposal profiles, pricing policies, and modules.",columns:["Setting","Current Alpha Decision","Status"],rows:[["Primary Green","#4B6623","Locked"],["Quote Start Version","0.0","Locked"],["Access Scope","Assigned Only / All","Locked"]]}
} as const;
export default async function SectionPage({params}:{params:Promise<{section:string}>}) { const {section}=await params; const cfg=sections[section as keyof typeof sections]; if(!cfg) notFound(); return <AppShell><PageHeader eyebrow={cfg.eyebrow} title={cfg.title} description={cfg.description} action={"action" in cfg?cfg.action:undefined}/><section className="panel"><div className="toolbar"><input placeholder={`Search ${cfg.title.toLowerCase()}...`}/><button>Filters</button></div><div className="tablewrap"><table><thead><tr>{cfg.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{cfg.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===0?<strong>{v}</strong>:v}</td>)}</tr>)}</tbody></table></div></section></AppShell>; }
